"""Readable renderings of a pre-registration, generated by code (no hand-written numbers).

- `render_proposal`: the full proposal for the athlete (Markdown, private), with provisional derived values and how
  they will change at activation.
- `plan_note_lines`: the plan to consult on the phone (Apple Notes): sessions, targets, deloads, minimal week.
  It deliberately leaves out health information (stop criteria, safety, exclusion reasons, body weight).
"""

from __future__ import annotations

from askesis.analytics.params import p
from askesis.reference import catalog
from askesis.validation.textcheck import _kb

DAYS = {"mon": "Lunedì", "tue": "Martedì", "wed": "Mercoledì", "thu": "Giovedì", "fri": "Venerdì", "sat": "Sabato",
        "sun": "Domenica"}


PHASES = {"fat_loss": "dimagrimento", "maintenance": "mantenimento", "muscle_gain": "aumento di massa",
          "recomposition": "ricomposizione"}
DIRECTIONS = {"decrease": "in calo", "increase": "in aumento", "stable": "stabile"}
UNIT_DECIMALS = {"kg": 1}


def _num(v: float, nd: int = 0) -> str:
    return f"{v:,.{nd}f}".replace(",", "§").replace(".", ",").replace("§", ".")


def _dec(v: float) -> str:
    return f"{v:g}".replace(".", ",")


def _ex_name(ex_id: str) -> str:
    e = next((e for e in catalog()["exercises"] if e["id"] == ex_id), None)
    return (e.get("name_it") or e["name"]) if e else ex_id


def _lift(it: dict) -> str:
    lo, hi = it["rep_range"]
    rir = it["target_rir"]
    note = f" ({it['note']})" if it.get("note") else ""
    return f"{_ex_name(it['exercise'])}: {it['sets']} × {lo}–{hi} @RIR {rir:g}{note}"


def _run(r: dict) -> str:
    parts = [f"corsa {'facile' if r.get('kind') == 'easy' else r.get('kind')}"]
    if r.get("duration_min"):
        parts.append(f"{r['duration_min']:g} min")
    if r.get("intensity") == "talk_test":
        parts.append("a talk test (frasi complete)")
    if r.get("note"):
        parts.append(f"— {r['note']}")
    return " ".join(parts)


def _session_lines(sessions: list[dict]) -> list[str]:
    out = []
    for s in sessions:
        out.append(f"{DAYS[s['day']]} — {s['name']}")
        out += [f"  • {_lift(it)}" for it in s.get("lifts", [])]
        if s.get("run"):
            out.append(f"  • {_run(s['run'])}")
    return out


MUSCLES_IT = {"chest": "petto", "front_delts": "deltoidi anteriori", "side_delts": "deltoidi laterali",
              "rear_delts": "deltoidi posteriori", "lats": "dorsali", "upper_back": "parte alta della schiena",
              "biceps": "bicipiti", "triceps": "tricipiti", "forearms": "avambracci", "quads": "quadricipiti",
              "glutes": "glutei", "hamstrings": "femorali", "adductors": "adduttori", "calves": "polpacci",
              "abs": "addominali", "spinal_erectors": "erettori spinali"}


def planned_volume(sessions: list[dict]) -> dict[str, dict[str, float]]:
    """Weekly working sets per muscle: direct (primary muscle only) and fractional (secondary counted by the
    catalog fraction, see claim rt.volume_dose_response)."""
    by_id = {e["id"]: e for e in catalog()["exercises"]}
    out: dict[str, dict[str, float]] = {}
    for sess in sessions:
        for it in sess.get("lifts", []):
            for muscle, frac in (by_id.get(it["exercise"], {}).get("muscles") or {}).items():
                v = out.setdefault(muscle, {"direct": 0.0, "fractional": 0.0})
                v["fractional"] += it["sets"] * frac
                if frac >= 1.0:
                    v["direct"] += it["sets"]
    return dict(sorted(out.items(), key=lambda kv: -kv[1]["fractional"]))


def volume_table(sessions: list[dict]) -> list[str]:
    L = ["| Gruppo muscolare | Serie dirette/sett. | Serie frazionarie/sett. |", "|---|---|---|"]
    for m, v in planned_volume(sessions).items():
        L.append(f"| {MUSCLES_IT.get(m, m)} | {v['direct']:g} | {_dec(v['fractional'])} |")
    return L


def _changes(data: dict, kind: str) -> list[dict]:
    return [c for c in data.get("plan_changes", []) if c["kind"] == kind]


def _value(content_value, preview: dict | None, unit: str) -> str:
    if isinstance(content_value, str) and content_value.startswith("$derived:"):
        name = content_value.removeprefix("$derived:")
        v = (preview or {}).get("values", {}).get(name)
        if not v:
            return f"da calcolare all'attivazione ({unit})"
        return f"~{_num(v['value'])} {unit} (provvisorio)" if not (preview or {}).get("frozen") else (
            f"{_num(v['value'])} {unit}")
    return f"{_num(content_value)} {unit}"


def _link(source_id: str) -> str:
    _, sources = _kb()
    s = sources.get(source_id, {})
    if s.get("doi"):
        return f"[{source_id}](https://doi.org/{s['doi']})"
    if s.get("pmid"):
        return f"[{source_id}](https://pubmed.ncbi.nlm.nih.gov/{s['pmid']}/)"
    return source_id


def render_proposal(title: str, data: dict, preview: dict | None, preview_error: str | None = None) -> str:
    derived = data.get("derived") or {}
    L = [f"# Proposta — {title}", "",
         f"> Generata dal codice dalla pre-registrazione. Avvio {data['start_date']} · valutazioni intermedie "
         f"{', '.join(str(d) for d in data.get('interim_checks', [])) or '—'} · valutazione finale "
         f"{data['evaluation_date']}. **Nulla cambia senza \"approvo\".**", "",
         "## Cosa cambia", data["change_description"], "",
         "## Perché", data["reason"], "", f"**Ipotesi:** {data['hypothesis']}", ""]
    if derived:
        L += ["## Valori calcolati all'attivazione (oggi PROVVISORI)", "",
              f"Formule fissate ora; i numeri vengono ricalcolati **all'attivazione** con i soli dati fino al "
              f"**{derived['data_until']}** e poi congelati (non cambiano più).", ""]
        if preview_error:
            L.append(f"Valori attuali non calcolabili: {preview_error}")
        L += ["| Valore | Oggi (provvisorio) | Fonte oggi | Come verrà calcolato |", "|---|---|---|---|"]
        for d in derived["values"]:
            v = (preview or {}).get("values", {}).get(d["name"])
            now = f"{_num(v['value'], UNIT_DECIMALS.get(d['unit'], 0))} {d['unit']}" if v else "—"
            src = "formula"
            if v and v.get("source"):
                src = f"`{v['source'].split(' ')[0]}`" + (f" al {v['period_end']}" if v.get("period_end") else
                                                          " (ripiego dichiarato)")
            L.append(f"| {d['name']} | {now} | {src} | {d['description']} |")
        if preview:
            tdee = preview["values"].get("start_tdee", {}).get("detail") or {}
            default_factor = str(tdee.get("activity_factor_source", "")).startswith("default")
            if tdee.get("method") == "prior_only":
                L += ["", "Il mantenimento stimato è ancora **solo la formula di partenza** (metabolismo a riposo × "
                      f"fattore di attività {_dec(tdee['activity_factor']) if tdee.get('activity_factor') else '—'}, "
                      f"{'predefinito' if default_factor else 'dichiarato'}"
                      "): incertezza ampia. Le pesate fino alla data limite cambiano il peso di partenza e quindi "
                      "target calorico e proteico; la regola calorica rivaluta il target dopo 3 settimane."]
        starts = [d for d in derived["values"] if d["method"] == "energy_start"]
        if starts and preview and starts[0]["name"] in preview["values"]:
            st = preview["values"][starts[0]["name"]]
            L += ["", "Target di partenza: il più basso tra " + " e ".join(
                f"{'target da formula' if k == 'formula_target' else 'intake abituale − passo'} "
                f"({_num(v)} kcal/die)" for k, v in st["candidates"].items())
                + f" → oggi vincola **{'la formula' if st['bound'] == 'formula_target' else 'l intake abituale'}**."
                .replace("l intake", "l'intake")]
        L.append("")
    for c in _changes(data, "phase"):
        ph = c["content"]
        L += ["## Fase", f"{PHASES.get(ph['phase'], ph['phase'])} dal {c['valid_from']} · durata massima "
              f"{ph['max_duration_weeks']} settimane · poi {PHASES.get(ph['next_phase'], ph['next_phase'])}", "",
              "Criteri di uscita:"]
        L += [f"- {e['description']}" for e in ph["exit_criteria"]]
        L.append("")
    for c in _changes(data, "nutrition_target"):
        t = c["content"]
        b = t.get("protein_basis", {})
        L += ["## Nutrizione", f"- Energia: {_value(t['energy_kcal'], preview, 'kcal/die')}",
              f"- Proteine: {_value(t['protein_g'], preview, 'g/die')} — base {_dec(b['g_per_kg'])} g/kg "
              f"di {'peso corporeo' if b.get('method') == 'per_kg_body_weight' else b.get('method', '—')}"]
        if b.get("uncertainty"):
            L.append(f"- Incertezza: {b['uncertainty']}")
        L.append("")
    for c in _changes(data, "programme"):
        pg = c["content"]
        L += ["## Allenamento", f"Progressione: `{pg.get('progression_rule')}` (L1, automatica). Deload pianificati: "
              f"{', '.join(str(d) for d in pg.get('deload_weeks', [])) or '—'}."]
        if pg.get("pain_gate"):
            g = pg["pain_gate"]
            L.append(f"Blocco della progressione: sugli schemi {', '.join(g['patterns'])} il carico non aumenta se nei "
                     f"{g['lookback_days']} giorni precedenti è registrato dolore ({', '.join(g['regions'])}) sopra "
                     f"{_dec(g['max_score'])}/10 (sotto la soglia di safety, che invece ferma il movimento).")
        L.append("")
        L += _session_lines(pg["microcycle"])
        L += ["", "**Volume settimanale pianificato** (serie allenanti; frazionarie = muscoli secondari contati 0,5, "
              "come in `rt.volume_dose_response`; esercizi e muscoli dal catalogo):", ""]
        L += volume_table(pg["microcycle"])
        L += ["", "**Settimana minima** (settimane difficili):"]
        L += _session_lines(pg["minimal_week"]) + [""]
    eo = data["expected_outcome"]
    L += ["## Come si valuta",
          f"- Esito atteso: `{eo['metric_id']}` {DIRECTIONS.get(eo['direction'], eo['direction'])}, intervallo "
          f"{_dec(eo['expected_range'][0])} … {_dec(eo['expected_range'][1])}",
          f"- Successo: {data['success_criteria']}",
          "- Aderenza minima: " + ", ".join(f"{k} {v:.0%}" for k, v in data.get("min_adherence", {}).items()),
          "", "## Criteri di stop"]
    L += [f"- {s}" for s in data["stop_criteria"]]
    claims, _ = _kb()
    L += ["", "## Evidenze"]
    for cid in data.get("evidence_claims", []):
        c = claims.get(cid, {})
        L.append(f"- `{cid}` ({c.get('certainty', '—')}): {' '.join(str(c.get('claim', '')).split())} — "
                 + ", ".join(_link(s) for s in c.get("sources", [])))
    for label, key in (("Opinione esperta", "expert_opinion"), ("Preferenza personale", "personal_preference")):
        if data.get(key):
            L += ["", f"## {label}"] + [f"- {x}" for x in data[key]]
    return "\n".join(L) + "\n"


def plan_note_lines(title: str, data: dict, preview: dict | None, provisional: bool = True) -> list[str]:
    """Plan for the phone: no health information."""
    L = [f"Askesis · Piano — {title}"]
    tag = " (provvisorio fino all'attivazione)" if provisional else ""
    L.append(f"Dal {data['start_date']} · valutazione finale {data['evaluation_date']}{tag}")
    for c in _changes(data, "phase"):
        ph = c["content"]
        L += ["", f"FASE: {PHASES.get(ph['phase'], ph['phase'])} · max {ph['max_duration_weeks']} settimane · poi "
              f"{PHASES.get(ph['next_phase'], ph['next_phase'])}"]
    for c in _changes(data, "nutrition_target"):
        t = c["content"]
        L += ["", "NUTRIZIONE",
              f"Energia: {_value(t['energy_kcal'], preview, 'kcal/die')}",
              f"Proteine: {_value(t['protein_g'], preview, 'g/die')}"]
    for c in _changes(data, "programme"):
        pg = c["content"]
        L += ["", "SETTIMANA TIPO"] + _session_lines(pg["microcycle"])
        L += ["", "PROGRESSIONE",
              "Doppia progressione: stesso carico finché tutte le serie arrivano al massimo del range al RIR "
              f"indicato per {p('double_progression_exposures')} sedute di fila, poi si aumenta il carico.",
              "Deload (meno serie, più RIR): settimane del " + ", ".join(str(d) for d in pg.get("deload_weeks", []))]
        L += ["", "SETTIMANA MINIMA (settimane difficili)"] + _session_lines(pg["minimal_week"])
        if pg.get("constraints", {}).get("week_1"):
            L += ["", f"Settimana 1 — {pg['constraints']['week_1']}"]
    return L
